---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create S3 Bucket for Deployment Files'

Resources:
  rS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "vf-pcs-deploy-${AWS::Region}-${AWS::AccountId}"
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256